import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx,js,jsx}",
    "./components/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#141b2b",
        "on-primary-container": "#582200",
        "on-tertiary-fixed": "#002109",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-variant": "#2e3545",
        "on-tertiary-fixed-variant": "#005320",
        "on-primary": "#552100",
        "inverse-surface": "#dce2f7",
        "tertiary": "#62df7d",
        "on-primary-fixed-variant": "#783200",
        "secondary-fixed": "#e1e0ff",
        "surface-container-high": "#232a3a",
        "tertiary-container": "#2cb055",
        "outline": "#a78b7d",
        "surface-container-highest": "#2e3545",
        "secondary-fixed-dim": "#c0c1ff",
        "primary-fixed": "#ffdbca",
        "tertiary-fixed": "#7ffc97",
        "surface-dim": "#0c1322",
        "on-error": "#690005",
        "surface-tint": "#ffb690",
        "on-secondary": "#1000a9",
        "secondary-container": "#3131c0",
        "on-surface-variant": "#e0c0b1",
        "on-primary-fixed": "#341100",
        "tertiary-fixed-dim": "#62df7d",
        "primary": "#ffb690",
        "on-surface": "#dce2f7",
        "inverse-on-surface": "#293040",
        "on-error-container": "#ffdad6",
        "secondary": "#c0c1ff",
        "on-background": "#dce2f7",
        "surface-container-lowest": "#070e1d",
        "error-container": "#93000a",
        "background": "#0c1322",
        "primary-container": "#f97316",
        "surface-bright": "#323949",
        "on-secondary-fixed": "#07006c",
        "outline-variant": "#584237",
        "on-secondary-container": "#b0b2ff",
        "inverse-primary": "#9d4300",
        "primary-fixed-dim": "#ffb690",
        "on-tertiary-container": "#003b15",
        "on-tertiary": "#003914",
        "error": "#ffb4ab",
        "surface-container": "#191f2f",
        "surface": "#0c1322",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      keyframes: {
        "pulse-flame": {
          "0%, 100%": { transform: "scale(1)", filter: "drop-shadow(0 0 15px rgba(249,115,22,0.4))" },
          "50%": { transform: "scale(1.05)", filter: "drop-shadow(0 0 25px rgba(249,115,22,0.7))" },
        },
        "odometer-in": {
          "0%": { transform: "translateY(40%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "slide-in-top": {
          "0%": { transform: "translateY(-10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "confetti-fall": {
          "0%": { transform: "translateY(-20vh) rotate(0deg)", opacity: "1" },
          "100%": { transform: "translateY(110vh) rotate(720deg)", opacity: "0" },
        },
      },
      animation: {
        "pulse-flame": "pulse-flame 2s ease-in-out infinite",
        "odometer-in": "odometer-in 300ms ease-out",
        "slide-in-top": "slide-in-top 300ms ease-out",
        "confetti-fall": "confetti-fall 2.5s linear forwards",
      },
    },
  },
  plugins: [],
};

export default config;
